# Generated by Django 4.2.6 on 2023-11-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('schedule_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
