# Generated by Django 4.2.6 on 2023-11-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_lecture_remove_schedule_instructor_delete_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='schedule_date',
        ),
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
